name: Update Feeds

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:          # allow manual run

permissions:
  contents: write            # allow committing items.json

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Collect feeds
        run: python collect.py

      - name: Show items head (debug)
        run: |
          echo "---- items.json head ----"
          head -n 80 items.json || true

      - name: Commit items.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add items.json
          git commit -m "Auto update items.json" || echo "No changes"
          git pull --rebase || true
          git push || true
