name: Update Feeds

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:          # lets you run it manually from Actions

# IMPORTANT: allow the workflow to push items.json back to the repo
permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Collect feeds
        run: python collect.py

      - name: Commit items.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add items.json
          git commit -m "Auto update items.json" || echo "No changes"
          # avoid push races with pages-build-deployment
          git pull --rebase || true
          git push || true
